### ISSUE TITLE
Error when trying to move through months

### ISSUE THREAD

**Issue by AguChaves92** [VDS13/telegram-inline-calendar#5] opened 2023-03-03 13:05 UTC
So when I press the advance button  to go to the next month nothing happens. it loads for a bit but neither the month nor the days change. And when i press it again, the bot simply crashes. Here is the error log:

![image](https://user-images.githubusercontent.com/85836863/222726915-aa061af6-7c30-42ed-88b5-8212016ee6a5.png). 

Also when I press the go back button it changes to january and skips february. And the it gets stuck on january and it cant advance back to march.

**Comment by VDS13** [comment] 2023-03-03 15:21
Could you show what package options you are using so I can simulate the situation?

**Comment by AguChaves92** [comment] 2023-03-03 17:37
here's the code
![image](https://user-images.githubusercontent.com/85836863/222789619-51813b92-cb6a-4b1b-97e6-ceae9a8ac5e8.png)
![image](https://user-images.githubusercontent.com/85836863/222789650-5afffd13-7d90-4f8f-8f0f-c1b127f39efa.png)

**Comment by VDS13** [comment] 2023-03-03 17:46
> here's the code
> 
> ![image](https://user-images.githubusercontent.com/85836863/222789619-51813b92-cb6a-4b1b-97e6-ceae9a8ac5e8.png)
> 
> ![image](https://user-images.githubusercontent.com/85836863/222789650-5afffd13-7d90-4f8f-8f0f-c1b127f39efa.png)
> 
> 

Always on the same press? Many factors can play here: CPU load, Internet speed, problems on the telegram side, my badly optimized code :)

**Comment by VDS13** [comment] 2023-03-03 17:58
Try like this:
```js
bot.on("callback_query", (ctx) => {
    if (ctx.callbackQuery.message.message_id == calendar.chats.get(ctx.callbackQuery.message.chat.id)) {
        res = calendar.clickButtonCalendar(ctx.callbackQuery);
        if (res !== -1) {
            ctx.reply("You selected: " + res);
        }
    }
});
```

**Comment by AguChaves92** [comment] 2023-03-03 18:49
would a video of the behaviour help?


https://user-images.githubusercontent.com/85836863/222802572-a0abd891-6f51-466c-9b32-345cd7c52c01.mp4

this is with the code you passed.

**Comment by VDS13** [comment] 2023-03-03 20:12
> would a video of the behaviour help?
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/85836863/222802572-a0abd891-6f51-466c-9b32-345cd7c52c01.mp4
> 
> 
> 
> this is with the code you passed.

Can you try using a different Telegram Bot Api? I want to understand if the problem will repeat with another API, because I can not reproduce the problem.

**Comment by VDS13** [comment] 2023-03-04 12:53
The problem is most likely related to slow internet or api.telegram response.

**Comment by AguChaves92** [comment] 2023-03-06 11:49
I can't speak for the telegram api, but my internet isn´t as slow as to cause this kind of issues. But I don't know

**Comment by VDS13** [comment] 2023-03-06 17:55
Could you try using `node-telegram-bot-api` or `grammy` for testing? This is required to understand if the problem occurs when using other libraries. If the problem does not manifest itself, I will make changes to the package.

**Comment by AguChaves92** [comment] 2023-03-07 12:14
Ill try today and see what happens. Ill report back then

**Comment by VDS13** [comment] 2023-03-09 10:57
@AguChaves92, Are you using `type: "module"`? If yes, then at the moment the library does not support `ESM`, in the near future I will release an update to work with `ESM`.

**Comment by VDS13** [comment] 2023-03-16 11:16
@AguChaves92, can you try using the following version: `npm i telegram-inline-calendar@ecmascript`?

**Comment by VDS13** [comment] 2023-03-16 17:03
@AguChaves92, If you managed to make everything work, please consider closing this issue.

**Closed as completed** 2023-03-25 16:05 UTC
