### ISSUE TITLE
TypeError: NavCalendar is not a constructor

### ISSUE THREAD

**Issue by kpripper** [VDS13/telegram-inline-calendar#6] opened 2023-03-05 09:26 UTC
Hello, all options give errors. How to solve the problem?

1.

const NavCalendar = require('telegram-inline-calendar')                
---------------------------------
ReferenceError: require is not defined in ES module scope, you can use import instead

2. 

import { NavCalendar } from 'telegram-inline-calendar'
---------------------------------
SyntaxError: Named export 'NavCalendar' not found. The requested module 'telegram-inline-calendar' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using:
import pkg from 'telegram-inline-calendar';
const { NavCalendar } = pkg;

3. 

import pkg from 'telegram-inline-calendar'
const { NavCalendar } = pkg
console.log(pkg)
const calendar = new NavCalendar(bot, {
  date_format: 'MMM D, YYYY h:mm A',
  language: 'de',
  start_week_day: 1,
  bot_api: "telebot",
  time_selector_mod: true,
  time_range: "08:00-15:59",
  time_step: "15m"
});
---------------------------------
[class Calendar]
TypeError: NavCalendar is not a constructor

4. 

import * as pkg from 'telegram-inline-calendar'
const { NavCalendar } = pkg
console.log(pkg)
---------------------------------
[Module: null prototype] { default: [class Calendar] }
TypeError: NavCalendar is not a constructor

**Comment by VDS13** [comment] 2023-03-05 09:45
Hello,
The problem is related to incorrect interaction with TypeScript.
I'll fix it in a few hours.

**Comment by VDS13** [comment] 2023-03-05 14:56
@kpripper, hello,
At the moment, the package does not support `ES module`, I will release an update with support in the near future.
Now, to use the package, you need to remove the line `type: module` from `package.json`.
I apologize for the inconvenience.

**Comment by VDS13** [comment] 2023-03-16 11:16
@kpripper, can you try using the following version: `npm i telegram-inline-calendar@ecmascript`?

**Comment by VDS13** [comment] 2023-03-16 17:03
@kpripper, If you managed to make everything work, please consider closing this issue.

**Closed as completed** 2023-03-25 16:05 UTC
